### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by ethanwhite** [weecology/livedat#1]
*Notes on suggested improvements from @dapperstats.*

Consider adding "and having an active GitHub account" (with a link?) to "This assumes a basic knowledge...". Also consider adding a link on "basic knowledge" to carpentry course?

The size of the "import your project to github" image, along with the font, make it look like that's actually another header in the README. Consider resizing it a little maybe?

step 5 under "connect to travis" has a dead (or secret?) hyperlinked page behind "screenshot of approving repository access"

i think it's worth it to call out the connection is to travis-ci.com rather than .org, i didn't catch that at first and was wondering why my account looked a little different

"You will be redirected to Travis. Click the `Sign in with GitHub button and your done." -> "You will be redirected to Travis. Click the `Sign in with GitHub` button and you're done."

Select `Developer` Settings from the bottom of the `Personal settings menu on the left of the screen -> Select `Developer` Settings from the bottom of the `Personal` settings menu on the left of the screen

highlight the icon maybe for "Click the copy icon to the right of the long string of letters and numbers in the green box"

step 10 under "Give Travis access to update your data on GitHub " has a dead (or secret?) hyperlinked page behind "screenshot of more options menu of travis"

consider mentioning that pacman can grab github repositories as well, but will need another function to do that (as in portalPredictions does with portalr)

are you going to add thoughts on security? if not, i'd remove that header/section.

possible additonal steps to add:

do you want to provide steps to remove the template info from the repo? (like cleaning up the README and removing the screenshots folder?)
maybe as part of the README update mention the travis and zenodo badges?
what about adding the data?

*Suggested improvements from @ha0ye*

One of the screenshot files has a typo: `travsi_more_options_menu.png`

I'd also recommend doing a bit of colored markup on the screenshots to indicate what to do for that step. (e.g. in the very first screenshot, circling the box for the new repo name)

**Comment by gmyenni** [comment]
This can be closed. I've started making specific issues for remaining improvements.
