### ISSUE TITLE
Add some thoughts on security

### ISSUE THREAD

**Issue by gmyenni** [weecology/livedat#2]

**Comment by ethanwhite** [comment]
Now the only problem is I don't remember what we were thinking out when we added this...

:thinking: ... :thinking: ... :thinking: I think I was thinking about giving full GitHub account access to Travis and the potential value of having a separate deploy account (like we do).

**Comment by ethanwhite** [comment]
Done in 364f2d3ea98cde7044c24150de2aec806f66d701.
